name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Install Gradle 6.9
        run: |
          wget https://services.gradle.org/distributions/gradle-6.9-bin.zip
          unzip gradle-6.9-bin.zip
          sudo mv gradle-6.9 /opt/gradle

      - name: Build Project
        run: /opt/gradle/bin/gradle build
