name: Java CI with Gradle

on:
  push:
    branches: [ master ]

jobs:
  build-java:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Install Gradle
        run: sudo apt-get install gradle

      - name: Build with Gradle
        run: gradle build
